spring:
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/spring_db
    username: root
    password: 1234
  mvc:
    hiddenmethod:
      filter:
        enabled: true

mybatis:
  mapper-locations: classpath:mybatis/*.xml